name: with-defaults
on:
  pull_request:
  schedule:
    - cron: '0 8 * * 0'

jobs:
  with_defaults:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["22.04"]
        include:
          - name: "master"
            openstack_version: "master"
            ubuntu_version: "22.04"
            additional_services: "openstack-cli-server"
          - name: "epoxy"
            openstack_version: "stable/2025.1"
            ubuntu_version: "22.04"
            additional_services: ""
          - name: "dalmatian"
            openstack_version: "stable/2024.2"
            ubuntu_version: "22.04"
            additional_services: "openstack-cli-server"
          - name: "caracal"
            openstack_version: "stable/2024.1"
            ubuntu_version: "22.04"
            additional_services: ""
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: A job to deploy devstack with defaults
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout devstack-action
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy devstack
        uses: ./
        with:
          branch: ${{ matrix.openstack_version }}
          enabled_services: '${{ matrix.additional_services }}'
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: functional-basic-${{ matrix.name }}
          path: /tmp/devstack-logs/*
